name: Fast-LiO in ROS Noetic Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup ROS environment
      uses: ros-tooling/setup-ros@0.5.0
      with:
        required-ros-distributions: "noetic"

    - name: Build FAST-LIO dependencies
      run: |
        sudo apt update && sudo apt upgrade
        sudo apt-get install -y git cmake libgoogle-glog-dev libgflags-dev libatlas-base-dev libeigen3-dev libsuitesparse-dev wget
        wget http://ceres-solver.org/ceres-solver-2.1.0.tar.gz
        tar zxf ceres-solver-2.1.0.tar.gz
        mkdir ceres-bin
        cd ceres-bin
        cmake ../ceres-solver-2.1.0
        make -j2
        make test
        sudo make install
        sudo apt-get install -y libboost-all-dev python3-catkin-tools
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:borglab/gtsam-release-4.0 -y
        sudo apt-get update
        sudo apt-get install -y libgtsam-dev libgtsam-unstable-dev

    - name: Build FAST-LIO in workspace
      run: |
        sudo mkdir -p /catkin_ws/src
        sudo cp -r FAST_LIO /catkin_ws/src/FAST_LIO
        sudo cp -r livox_ros_driver /catkin_ws/src/livox_ros_driver
        cd /catkin_ws
        . /opt/ros/${ROS_DISTRO}/setup.sh
        rosdep update
        rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y
        catkin config --install
        catkin build
