name: Fast-LiO in ROS Noetic Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup ROS environment
      uses: ros-tooling/setup-ros@0.5.0
      with:
        required-ros-distributions: "noetic"
