name: Fast-LiO in ROS Noetic Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup ROS environment
      uses: ros-tooling/setup-ros@0.5.0
      with:
        required-ros-distributions: "noetic"

    - name: Build dependencies for fastlio
      run: |
          apt-get update
          apt-get install -y git cmake libgoogle-glog-dev libgflags-dev libatlas-base-dev libeigen3-dev libsuitesparse-dev wget
          wget http://ceres-solver.org/ceres-solver-2.1.0.tar.gz && tar zxf ceres-solver-2.1.0.tar.gz
          mkdir ceres-bin
          cd ceres-bin
          cmake ../ceres-solver-2.1.0
          make -j2
          make test
          make install